/** Decoders for the compact tables generated by tests/server/fixtures/capture-python.py. */

export type Ranges = Uint32Array;

/** "a-b,c" hex ranges as a flat sorted [start, end, start, end, ...] array. */
export function decodeRanges(text: string): Ranges {
  const items = text ? text.split(",") : [];
  const result = new Uint32Array(items.length * 2);
  items.forEach((item, index) => {
    const [start, end = start] = item.split("-");
    result[index * 2] = parseInt(start, 16);
    result[index * 2 + 1] = parseInt(end, 16);
  });
  return result;
}

export function inRanges(ranges: Ranges, codePoint: number): boolean {
  let low = 0;
  let high = ranges.length / 2 - 1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    if (codePoint < ranges[middle * 2]) high = middle - 1;
    else if (codePoint > ranges[middle * 2 + 1]) low = middle + 1;
    else return true;
  }
  return false;
}

/** "cp:a b c,..." hex code point mappings. */
export function decodeMap(text: string): Map<number, string> {
  const result = new Map<number, string>();
  if (!text) return result;
  for (const item of text.split(",")) {
    const [key, value] = item.split(":");
    result.set(parseInt(key, 16), value ? String.fromCodePoint(...value.split(" ").map((part) => parseInt(part, 16))) : "");
  }
  return result;
}

/** "cp:n,..." hex code point to decimal number. */
export function decodeNumbers(text: string): Map<number, number> {
  const result = new Map<number, number>();
  for (const item of text.split(",")) {
    const [key, value] = item.split(":");
    result.set(parseInt(key, 16), Number(value));
  }
  return result;
}

/** Lazily decode a table on first use, so importing a module costs nothing. */
export function lazy<T>(build: () => T): () => T {
  let value: T | undefined;
  let built = false;
  return () => {
    if (!built) {
      value = build();
      built = true;
    }
    return value as T;
  };
}

/** Code points of a string, like iterating a Python str; lone surrogates stay single units. */
export function codePoints(text: string): number[] {
  const result: number[] = [];
  for (const character of text) result.push(character.codePointAt(0) as number);
  return result;
}
