"""Capture reference fast-chrome behavior for the TypeScript port.

Run once with the reference venv's Python, from a private temporary directory:

    tmp=$(mktemp -d "$TMPDIR/fc-capture-XXXXXX")
    mkdir "$tmp/home"
    cd "$tmp" && HOME="$tmp/home" CAPTURE_TEMP="$tmp" PYTHONDONTWRITEBYTECODE=1 \
      <reference>/.native-venv/bin/python -B <repo>/tests/server/fixtures/capture-python.py <reference> <repo>

The reference directory is only read. Registry, profile and socket roots are patched to the temporary
directory before any call, so nothing is written under the real home directory.
Outputs: tests/server/fixtures/python-*.json and src/server/unicode/*-table(s).ts.
"""

import ast
import asyncio
import base64
import io
import json
import os
import random
import sys
import sysconfig
from pathlib import Path

if len(sys.argv) != 3:
    raise SystemExit("usage: capture-python.py <reference-dir> <repo-dir>")
REFERENCE = Path(sys.argv[1]).resolve()
REPO = Path(sys.argv[2]).resolve()
TEMP = Path(os.environ["CAPTURE_TEMP"]).resolve()
if Path.home().resolve() != TEMP / "home" or Path.cwd().resolve() != TEMP:
    raise SystemExit("HOME must be $CAPTURE_TEMP/home and the working directory $CAPTURE_TEMP")
if not sys.dont_write_bytecode:
    raise SystemExit("run with python -B")
FIXTURES = REPO / "tests/server/fixtures"
UNICODE = REPO / "src/server/unicode"
sys.path.insert(0, str(REFERENCE))

import browser_pool  # noqa: E402

browser_pool.DEFAULT_ROOT = TEMP / "state/browser-pool"
browser_pool.BASE_ROOT = TEMP / "config/browser-pool"
browser_pool.SOCKET_ROOT = TEMP / "sockets"
for key in list(os.environ):
    if key.startswith("FAST_CHROME_") or key == "OPZERO_CHROME_HOST_SOCKET":
        del os.environ[key]
os.environ["OPZERO_CHROME_HOST_SOCKET"] = str(TEMP / "sockets/default.sock")

import encodings.idna  # noqa: E402
import ipaddress  # noqa: E402
import stringprep  # noqa: E402
import unicodedata  # noqa: E402
from urllib.parse import urlsplit  # noqa: E402

import pydantic_core  # noqa: E402
from PIL import Image  # noqa: E402

import native_server  # noqa: E402
import sites  # noqa: E402
from opchrome import Gate  # noqa: E402

ucd32 = unicodedata.ucd_3_2_0
MAX = 0x110000


def write_json(name, value):
    path = FIXTURES / name
    path.write_text(json.dumps(value, indent=2, ensure_ascii=True) + "\n")
    print(f"wrote {path.relative_to(REPO)}")


def outcome(function, *args):
    try:
        return {"ok": function(*args)}
    except Gate as error:
        return {"gate": error.code}
    except Exception as error:  # noqa: BLE001
        return {"error": type(error).__name__}


# --------------------------------------------------------------------------------------------- unicode tables

def ranges(predicate):
    result, start = [], None
    for cp in range(MAX):
        if predicate(cp):
            if start is None:
                start = cp
        elif start is not None:
            result.append((start, cp - 1))
            start = None
    if start is not None:
        result.append((start, MAX - 1))
    return result


def encode_ranges(items):
    return ",".join(f"{a:x}" if a == b else f"{a:x}-{b:x}" for a, b in items)


def encode_map(mapping):
    return ",".join(f"{cp:x}:" + " ".join(f"{ord(c):x}" for c in value) for cp, value in sorted(mapping.items()))


def ts_module(name, doc, constants):
    lines = ["// Generated by tests/server/fixtures/capture-python.py from CPython "
             f"{sys.version.split()[0]} (Unicode {unicodedata.unidata_version}). Do not edit.", f"// {doc}", ""]
    for key, value in constants:
        lines.append(f"export const {key} =\n  {json.dumps(value)};")
        lines.append("")
    (UNICODE / name).write_text("\n".join(lines))
    print(f"wrote {(UNICODE / name).relative_to(REPO)}")


def generate_idna_tables():
    chars = [chr(cp) for cp in range(MAX)]
    b2 = {}
    for cp, ch in enumerate(chars):
        mapped = stringprep.map_table_b2(ch)
        if mapped != ch:
            b2[cp] = mapped
    prohibited = ranges(lambda cp: any(test(chars[cp]) for test in (
        stringprep.in_table_c12, stringprep.in_table_c22, stringprep.in_table_c3, stringprep.in_table_c4,
        stringprep.in_table_c5, stringprep.in_table_c6, stringprep.in_table_c7, stringprep.in_table_c8,
        stringprep.in_table_c9)))
    decomposition = {}
    for cp, ch in enumerate(chars):
        full = ucd32.normalize("NFKD", ch)
        if full != ch:
            decomposition[cp] = full
    # CPython's 3.2.0 normalization reorders and composes with the current combining classes and composition
    # table (Modules/unicodedata.c nfd_nfkd and nfc_nfkc use _getrecord_ex); only decomposition is versioned.
    combining = {}
    for cp, ch in enumerate(chars):
        value = unicodedata.combining(ch)
        if value:
            combining[cp] = value
    compose = {}
    for cp, ch in enumerate(chars):
        if 0xAC00 <= cp <= 0xD7A3:
            continue
        mapping = unicodedata.decomposition(ch)
        if not mapping or mapping.startswith("<"):
            continue
        parts = [chr(int(part, 16)) for part in mapping.split()]
        if len(parts) == 2 and unicodedata.normalize("NFC", parts[0] + parts[1]) == ch:
            compose[cp] = parts[0] + parts[1]
    ts_module("idna2003-tables.ts",
              "RFC 3454 stringprep tables B.1, B.2, C.1.2-C.9, D.1 and D.2 from Lib/stringprep.py, and the "
              "decompositions CPython's unicodedata.ucd_3_2_0.normalize uses.", [
                  ("B1", encode_ranges(ranges(lambda cp: stringprep.in_table_b1(chars[cp])))),
                  ("B2", encode_map(b2)),
                  ("PROHIBITED", encode_ranges(prohibited)),
                  ("D1", encode_ranges(ranges(lambda cp: stringprep.in_table_d1(chars[cp])))),
                  ("D2", encode_ranges(ranges(lambda cp: stringprep.in_table_d2(chars[cp])))),
                  ("NFKD_32", encode_map(decomposition)),
                  ("COMBINING", ",".join(f"{cp:x}:{value}" for cp, value in sorted(combining.items()))),
                  ("COMPOSE", encode_map(compose)),
              ])


def generate_case_tables():
    chars = [chr(cp) for cp in range(MAX)]
    lower = {cp: chars[cp].lower() for cp in range(MAX) if chars[cp].lower() != chars[cp] and cp != 0x3A3}
    casefold = {cp: chars[cp].casefold() for cp in range(MAX) if chars[cp].casefold() != chars[cp]}
    # Final_Sigma context classes, probed through str.lower() itself (Objects/unicodeobject.c
    # handle_capital_sigma): a case-ignorable character is skipped; otherwise its casedness decides.
    ignorable = []
    cased = []
    for cp in range(MAX):
        ch = chars[cp]
        before_final = (ch + "\u03a3").lower().endswith("\u03c2")
        after_final = ("A\u03a3" + ch + "A").lower().startswith("a\u03c2")
        if before_final:
            cased.append(cp)
        elif not after_final:
            ignorable.append(cp)
    ignorable_set, cased_set = set(ignorable), set(cased)
    ts_module("casefold-table.ts",
              "Python str.lower(), str.casefold(), str.isspace(), str.isalnum() and the Final_Sigma classes.", [
                  ("LOWER", encode_map(lower)),
                  ("CASEFOLD", encode_map(casefold)),
                  ("SPACE", encode_ranges(ranges(lambda cp: chars[cp].isspace()))),
                  ("ALNUM", encode_ranges(ranges(lambda cp: chars[cp].isalnum()))),
                  ("CASE_IGNORABLE", encode_ranges(ranges(lambda cp: cp in ignorable_set))),
                  ("CASED", encode_ranges(ranges(lambda cp: cp in cased_set))),
              ])


# --------------------------------------------------------------------------------------------- unicode corpus

def unicode_corpus():
    rng = random.Random(20260928)
    pool = ("aAzZ09-._ßſİıΣσςẞǅﬀﬁ０９ＡＺａｚ。．｡・〇 \u00ad\u034f\u200b\u200c\u200d\u2060\ufeff\ufe00"
            "\u0301\u0308\u0323\u0327\u0345\u05b0\u0591\u0655\u093c\u0e38\u0f71\u302a\u3099"
            "éèêëÅåÇçÑñŞşǄǆǈ가각갂각한글\u1100\u1161\u11a8ｶﾞｸﾞ㌀㍻ⅷ①⑴⒜㈱℡™ℌℍℕ℀℁℅"
            "αβγΑΒΓάΆΐΰᾳᾼῳῼ ﬃﬄĲĳŉǰ ΐ ΰ ǰ ẖ ẗ ẘ ẙ ẚ ﬅﬆﬓ"
            "שלוםعربي\u200e\u200f\u202a\u202e٠١٢\u0660\u06f0"
            "\u2028\u2029\u0085\u00a0\u1680\u2000\u200a\u3000\u180e\u001c\u001f\t\n\x0b\x0c\r"
            "\U0001d400\U0001d7ce\U0001f600\U0001f1e6\U00010400\U00010428\U0001e900\U0001e922"
            "\ud800\udfff\ue000\uf8ff\ufffd\ufffe\U000e0001\U000e0020\U000e007f\U0010fffd"
            "ⱼₐᵃᴬ\u2c7c\ua7cb\ua7cc\ua7da\u1e9e\u0130\u0131\u01c5\u1f88\u1fbc")
    samples = sorted({"".join(rng.choice(pool) for _ in range(rng.randint(1, 8))) for _ in range(900)})
    fixed = ["münchen", "MÜNCHEN", "straße", "公司", "ﬀ", "ⅷ", "①", "Å", "Å", "é", "é", "가", "각", "한글",
             "\u1100\u1161\u11a8", "ΣΑΣ", "ὈΔΥΣΣΕΎΣ", "aΣ", "Σa", "a\u0345Σ", "İstanbul", "ǅ", "ﬃ",
             "\u0061\u0323\u0302", "\u0061\u0302\u0323", "\u1e0b\u0323", "\u0071\u0307\u0323",
             "\u05d0\u05b8", "\u0928\u093c", "\u0f71\u0f72", "\u0f73", "\u2c7c", "\ua7cb", "\U0001d400"]
    cases = []
    for value in fixed + samples:
        folded_lower = value.lower()
        cases.append({
            "input": value,
            "nfkc32": ucd32.normalize("NFKC", value),
            "lower": folded_lower,
            "casefold": value.casefold(),
            "strip": value.strip(),
            "isspace": [c.isspace() for c in value],
            "isalnum": [c.isalnum() for c in value],
            "len": len(value),
            "idna": outcome(lambda v: v.encode("idna").decode("ascii"), value),
            "nameprep": outcome(encodings.idna.nameprep, value),
            "punycode": outcome(lambda v: v.encode("punycode").decode("ascii"), value),
        })
    write_json("python-unicode.json", {"python": sys.version.split()[0],
                                       "unicode": unicodedata.unidata_version, "cases": cases})


# --------------------------------------------------------------------------------------------- URL corpus

URLS = [
    "https://example.com/", "https://example.com", "https://EXAMPLE.com/", "HTTPS://Example.COM/path",
    "https://example.com:443/", "https://example.com:8443/", "https://example.com:0/", "https://example.com:65535/",
    "https://example.com:65536/", "https://example.com:99999/", "https://example.com:/", "https://example.com:+80/",
    "https://example.com:-1/", "https://example.com:0080/", "https://example.com:８０/", "https://example.com:8a/",
    "http://example.com/", "http://example.com:80/", "http://example.com:8080/", "ftp://example.com/",
    "https://user@example.com/", "https://user:pass@example.com/", "https://:pass@example.com/", "https://@example.com/",
    "https://user@:80/", "https://a@b@example.com/", "https://example.com@evil.test/", "https://user:@example.com/",
    "https://127.0.0.1/", "http://127.0.0.1/", "http://127.0.0.1:5173/", "http://localhost/", "http://localhost:3000/x",
    "http://LOCALHOST/", "http://localhost./", "http://127.0.0.2/", "http://[::1]/", "http://[::1]:3000/",
    "https://[::1]/", "https://[2001:DB8::1]/", "https://[2001:db8::1]:8443/x", "https://[::ffff:1.2.3.4]/",
    "https://[fe80::1%25eth0]/", "https://[fe80::1%eth0]/", "https://[fe80::1%ETH0]/", "https://[v1.x]/",
    "https://[v1x]/", "https://[1.2.3.4]/", "https://[::1/", "https://::1]/", "https://[::1]x/", "https://x[::1]/",
    "https://[::1]:x/", "https://[not-ip]/", "https://[::1]]/", "https://[[::1]/", "https://[]/",
    "https://1.2.3/", "https://01.2.3.4/", "https://1.2.3.256/", "https://0x7f.0.0.1/", "https://1.2.3.4.5/",
    "https://example.com./", "https://example.com../", "https://.example.com/", "https://a..b/", "https:///path",
    "https://", "https:", "https:example.com", "//example.com/", "example.com", "example.com/path", "/path",
    "https://example.com/path?query#fragment", "https://example.com?x", "https://example.com#x",
    "https://example.com/p#frag?x", "https://ex%41mple.com/", "https://ex ample.com/", "https://ex\tample.com/",
    "https://ex\nample.com/", " https://example.com/", "https://example.com/ ", "\x00https://example.com/",
    "https://a.com\\@b.com/", "https://a.com\\b/", "https://-a.com/", "https://a-.com/", "https://_a.com/",
    "https://a_b.com/", "https://münchen.de/", "https://MÜNCHEN.de/", "https://xn--mnchen-3ya.de/",
    "https://XN--MNCHEN-3YA.de/", "https://straße.de/", "https://www.公司.cn/", "https://公司.cn/",
    "https://例え.テスト/", "https://ａｂｃ.com/", "https://abc。com/", "https://abc．com/", "https://abc｡com/",
    "https://a\u00adb.com/", "https://a\u200bb.com/", "https://a\u200db.com/", "https://ΣΑΣ.gr/", "https://İ.com/",
    "https://ﬀ.com/", "https://ⅷ.com/", "https://①.com/", "https://ℌ.com/", "https://℀.com/", "https://a℁b.com/",
    "https://a＠b.com/", "https://a／b.com/", "https://a：b.com/", "https://a？b.com/", "https://a＃b.com/",
    "https://שלום.co.il/", "https://عربي.com/", "https://aשלום.com/", "https://שלוםa.com/",
    "https://\u0660.com/", "https://xn--.com/", "https://xn--a.com/", "https://xn--ab-.com/",
    "https://xn--münchen.de/", "https://\u2028.com/", "https://\ufffd.com/", "https://\U0001f600.com/",
    "https://" + "a" * 63 + ".com/", "https://" + "a" * 64 + ".com/", "https://" + "a." * 126 + "com/",
    "https://" + "a." * 127 + "com/", "https://" + "é" * 30 + ".com/", "https://" + "é" * 60 + ".com/",
    "https://deploy-preview-1704--example.netlify.app/login", "https://netlify.app/", "https://a.b.example.co.uk/",
    "https://foo.github.io/", "https://github.io/", "https://a.unlisted-tld/", "https://intranet/",
    "https://a.b.ck/", "https://b.ck/", "https://www.ck/", "https://x.www.ck/", "https://ck/",
    "https://x.y.kawasaki.jp/", "https://city.kawasaki.jp/", "https://a.city.kawasaki.jp/",
    "https://staging.dashboard.example.global/", "https://STAGING.Dashboard.EXAMPLE.global.:443/",
    "https://s3.amazonaws.com/", "https://bucket.s3.amazonaws.com/", "https://a.blogspot.com/",
    "https://com/", "https://co.uk/", "https://uk/", "https://example.xn--p1ai/", "https://пример.рф/",
    "https://sub.пример.рф/", "https://a.b.c.d.e.example.com/", "https://1.example.com/",
    "https://123/", "https://1e1/", "https://example.123/", "https://example.com:443:443/",
    "https://[::1]:443:1/", "https://example.com%2F/", "https://a%00b.com/", "https://a:b:c@d.com/",
    "javascript:alert(1)", "data:text/html,x", "about:blank", "file:///etc/passwd", "chrome://settings",
    "https:/example.com", "https:\\\\example.com", "HtTpS://ExAmPlE.CoM:443", "https://example.com:443",
    "http://127.0.0.1:80/", "http://[::1]:80/", "http://127.0.0.1:0/", "http://127.1/",
    "http://0.0.0.0/", "http://[::]/", "http://[0:0:0:0:0:0:0:1]/", "http://[::ffff:127.0.0.1]/",
    "http://[::127.0.0.1]/", "http://[1:2:3:4:5:6:7:8]/", "http://[1:2:3:4:5:6:7:8:9]/", "http://[1::2::3]/",
    "http://[:1::2]/", "http://[1::2:]/", "http://[12345::1]/", "http://[g::1]/", "http://[1:2:3:4:5:6:1.2.3.4]/",
    "http://[1:2:3:4:5:1.2.3.4]/", "http://[::1.2.3.04]/", "http://[1:0:0:0:0:0:0:0]/", "http://[1:0:0:1:0:0:0:1]/",
    "http://[0:0:1:0:0:1:0:0]/", "http://[fe80::%eth0]/", "http://[fe80::1%]/", "http://[fe80::1%a%b]/",
    "https://x" * 3, "https://a.b.c/" + "p" * 8200, "https://" + "b" * 250 + "/", "https://example.com:1/",
    "https://app.vercel.app/", "https://x.pages.dev/", "https://a.b.herokuapp.com/", "https://my.cloudfront.net/",
    "https://a.appspot.com/", "https://a.b.azurewebsites.net/", "https://x.github.io:443/", "https://x.gov.uk/",
    "https://a.b.sch.uk/", "https://www.example.com.au/", "https://example.com.br/", "https://x.kyoto.jp/",
    "https://a.b.c.kyoto.jp/", "https://x.bd/", "https://y.x.bd/", "https://z.y.x.bd/", "https://test.er/",
    "https://a.test.er/", "https://x.nom.br/", "https://a.x.nom.br/", "https://xn--o3cw4h.com/", "https://ไทย.com/",
    "https://a.ไทย/", "https://www.食狮.公司.cn/", "https://BÜCHER.example/", "https://bücher.example:8443/p",
    "https://user:pa:ss@example.com/", "https://us%40er@example.com/", "https://[::1]:0/", "https://[::1]:65536/",
    "https://[::ffff:0:0]/", "https://[2001:db8:0:0:1:0:0:1]/", "https://[2001:0db8::0001]/", "https://[::1%25lo]/",
    "https://[v7.fe80::1]/", "https://[vF.x]/", "https://[v.x]/", "https://example.com:8080:/",
    "https://example.com/%zz", "https://ex:ample.com/", "https://:443/", "https://@/", "https://a@/",
    "https://127.0.0.1:443/", "https://127.000.0.1/", "https://255.255.255.255/", "https://256.0.0.1/",
    "http://localhost:0/", "http://localhost:65535/", "http://localhost:65536/", "http://[::1]:65535/",
    "HTTP://LOCALHOST:3000/", "http://LocalHost./x", "https://xn--LOCALHOST/", "wss://example.com/",
]

HOSTS = [
    "example.com", "EXAMPLE.COM", "example.com.", "example.com..", ".example.com", "example.global", "Example.Global",
    "staging.example.global", "staging.dashboard.example.global.", "localhost", "LOCALHOST", "localhost.", "127.0.0.1",
    "127.0.0.1.", "::1", "[::1]", "[::1", "::1]", "2001:DB8::1", "[2001:DB8::1]", "::ffff:1.2.3.4",
    "fe80::1%eth0", "fe80::1%ETH0", "1.2.3", "01.2.3.4", "1.2.3.256", "münchen.de", "straße.de", "公司.cn",
    "www.公司.cn", "ａｂｃ.com", "abc。com", "a..b", "-a.com", "a-.com", "_a.com", "a_b.com", "ex ample.com",
    "a.com\\@b.com", "", "a" * 63 + ".com", "a" * 64 + ".com", "a." * 126 + "com", "a." * 127 + "com", "x" * 9000,
    "netlify.app", "deploy-preview-1704--example.netlify.app", "a.b.ck", "www.ck", "x.www.ck", "city.kawasaki.jp",
    "a.city.kawasaki.jp", "com", "co.uk", "github.io", "foo.github.io", "intranet", "a.unlisted-tld", "xn--",
    "xn--mnchen-3ya.de", "XN--MNCHEN-3YA.DE", "ΣΑΣ.gr", "İ.com", "user@example.com", "example.com:443",
    "example.com:x", "https://", "//example.com", "a.b", "a..", "..", ".", "0", "1", "a", "1e1", "0x7f.0.0.1",
    "\u0660.com", "שלום.co.il", "aשלום.com", "a\u00adb.com", "a\u200bb.com", "\ufeffexample.com",
]


def url_record(value):
    record = {"input": value}
    try:
        parts = urlsplit(value)
        split = {"scheme": parts.scheme, "netloc": parts.netloc, "path": parts.path, "query": parts.query,
                 "fragment": parts.fragment, "username": parts.username, "password": parts.password,
                 "hostname": parts.hostname}
        try:
            split["port"] = parts.port
        except ValueError:
            split["port_error"] = True
        record["urlsplit"] = split
    except ValueError:
        record["urlsplit"] = {"error": "ValueError"}
    os.environ.pop("FAST_CHROME_ALLOW_LOOPBACK", None)
    record["origin"] = outcome(native_server.origin, value)
    os.environ["FAST_CHROME_ALLOW_LOOPBACK"] = "1"
    record["origin_loopback"] = outcome(native_server.origin, value)
    os.environ.pop("FAST_CHROME_ALLOW_LOOPBACK", None)
    record["ascii_host"] = outcome(sites.ascii_host, value)
    record["cookie_site"] = outcome(sites.cookie_site, value)
    record["valid_site"] = sites.valid_site(value)
    record["ip_literal"] = sites.ip_literal(value)
    try:
        record["ip_address"] = str(ipaddress.ip_address(value))
    except ValueError:
        record["ip_address"] = None
    return record


def url_corpus():
    values = list(dict.fromkeys(URLS + HOSTS))
    records = [url_record(value) for value in values]
    extra = []
    for value in (None, 5, True, 1.5, [], {}):
        extra.append({"input": value, "ascii_host": outcome(sites.ascii_host, value),
                      "cookie_site": outcome(sites.cookie_site, value), "valid_site": sites.valid_site(value),
                      "origin": outcome(native_server.origin, value)})
    write_json("python-urls.json", {"cases": records, "non_strings": extra})


# --------------------------------------------------------------------------------------------- JPEG corpus

def pillow_verdict(data):
    try:
        with Image.open(io.BytesIO(data)) as image:
            image.verify()
            return {"format": image.format, "width": image.width, "height": image.height}
    except Exception as error:  # noqa: BLE001
        return {"error": type(error).__name__}


def segment(marker, payload):
    return bytes([0xFF, marker]) + (len(payload) + 2).to_bytes(2, "big") + payload


def sof(width, height, layers=3, bits=8, marker=0xC0, extra=b""):
    components = b"".join(bytes([i + 1, 0x11, 0]) for i in range(layers))
    return segment(marker, bytes([bits]) + height.to_bytes(2, "big") + width.to_bytes(2, "big")
                   + bytes([layers]) + components + extra)


SOS = segment(0xDA, bytes([1, 1, 0, 0, 63, 0])) + b"\x00" * 8 + b"\xff\xd9"
SOI = b"\xff\xd8"


def encoded(mode, size, **options):
    buffer = io.BytesIO()
    Image.new(mode, size, "white" if mode != "CMYK" else (0, 0, 0, 0)).save(buffer, "JPEG", **options)
    return buffer.getvalue()


def jpeg_corpus():
    cases = []

    def add(name, data):
        cases.append({"name": name, "data": base64.b64encode(data).decode(), "verdict": pillow_verdict(data)})

    add("rgb-4x4", encoded("RGB", (4, 4)))
    add("rgb-17x9", encoded("RGB", (17, 9)))
    add("gray-8x8", encoded("L", (8, 8)))
    add("cmyk-5x3", encoded("CMYK", (5, 3)))
    add("progressive", encoded("RGB", (16, 16), progressive=True))
    add("optimized", encoded("RGB", (16, 16), optimize=True))
    add("with-icc", encoded("RGB", (4, 4), icc_profile=b"\x00" * 200))
    add("with-exif", encoded("RGB", (4, 4), exif=Image.Exif().tobytes()))
    exif = Image.Exif()
    exif[0x011A] = 300.0
    exif[0x0128] = 2
    add("with-exif-dpi", encoded("RGB", (4, 4), exif=exif.tobytes()))
    add("with-comment", encoded("RGB", (4, 4), comment=b"synthetic"))
    add("with-dpi", encoded("RGB", (4, 4), dpi=(96, 96)))
    mpo = io.BytesIO()
    Image.new("RGB", (4, 4)).save(mpo, "MPO", save_all=True, append_images=[Image.new("RGB", (4, 4))])
    add("mpo", mpo.getvalue())
    png = io.BytesIO()
    Image.new("RGB", (4, 4)).save(png, "PNG")
    add("png", png.getvalue())
    gif = io.BytesIO()
    Image.new("P", (4, 4)).save(gif, "GIF")
    add("gif", gif.getvalue())
    add("empty", b"")
    add("soi-only", SOI)
    add("prefix-only", b"\xff\xd8\xff")
    add("prefix-eof", b"\xff\xd8\xff\xe0")
    add("minimal", SOI + sof(4, 4) + SOS)
    add("minimal-no-eoi", SOI + sof(4, 4) + segment(0xDA, bytes([1, 1, 0, 0, 63, 0])))
    add("sos-truncated", SOI + sof(4, 4) + b"\xff\xda\x00\x10\x01")
    add("sos-before-sof", SOI + SOS)
    add("no-sos", SOI + sof(4, 4) + b"\xff\xd9")
    add("no-sos-eof", SOI + sof(4, 4))
    add("gray", SOI + sof(4, 4, layers=1) + SOS)
    add("cmyk", SOI + sof(4, 4, layers=4) + SOS)
    add("two-layers", SOI + sof(4, 4, layers=2) + SOS)
    add("five-layers", SOI + sof(4, 4, layers=5) + SOS)
    add("zero-layers", SOI + sof(4, 4, layers=0) + SOS)
    add("bits-12", SOI + sof(4, 4, bits=12) + SOS)
    add("zero-width", SOI + sof(0, 4) + SOS)
    add("zero-height", SOI + sof(4, 0) + SOS)
    add("max-dims", SOI + sof(65535, 65535) + SOS)
    add("5000x5000", SOI + sof(5000, 5000) + SOS)
    add("5001x5000", SOI + sof(5001, 5000) + SOS)
    add("25M-exact", SOI + sof(6250, 4000) + SOS)
    add("25M-plus", SOI + sof(6250, 4001) + SOS)
    for marker in (0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF, 0xDE):
        add(f"sof-{marker:02x}", SOI + sof(3, 2, marker=marker) + SOS)
    for marker in (0xC8, 0xD0, 0xD7, 0xD8, 0xD9, 0xF0, 0xFD, 0x01, 0x02, 0xBF, 0x4F):
        add(f"bare-{marker:02x}", SOI + bytes([0xFF, marker]) + sof(4, 4) + SOS)
    for marker in (0xC4, 0xCC, 0xDC, 0xDD, 0xDF, 0xE0, 0xE5, 0xEF, 0xFE):
        add(f"segment-{marker:02x}", SOI + segment(marker, b"synthetic-payload") + sof(4, 4) + SOS)
    add("fill-bytes", SOI + b"\xff\xff\xff" + sof(4, 4) + SOS)
    add("ff00", SOI + b"\xff\x00" + sof(4, 4) + SOS)
    add("junk-between", SOI + b"abc" + sof(4, 4) + SOS)
    add("junk-ff-eof", SOI + sof(4, 4) + b"\xff")
    add("sof-short", SOI + segment(0xC0, b"\x08\x00\x04") + SOS)
    add("sof-five", SOI + segment(0xC0, b"\x08\x00\x04\x00\x04") + SOS)
    add("sof-six", SOI + segment(0xC0, b"\x08\x00\x04\x00\x04\x03") + SOS)
    add("sof-partial-component", SOI + segment(0xC0, b"\x08\x00\x04\x00\x04\x03\x01") + SOS)
    add("sof-partial-component-2", SOI + segment(0xC0, b"\x08\x00\x04\x00\x04\x03\x01\x11") + SOS)
    add("sof-extra-component", SOI + sof(4, 4, extra=b"\x04\x11\x00") + SOS)
    add("sof-length-0", SOI + b"\xff\xc0\x00\x00" + sof(4, 4) + SOS)
    add("sof-length-1", SOI + b"\xff\xc0\x00\x01" + sof(4, 4) + SOS)
    add("length-truncated", SOI + b"\xff\xe0\x00")
    add("segment-overrun", SOI + b"\xff\xe0\x00\x40abc")
    add("dqt-8bit", SOI + segment(0xDB, b"\x00" + b"\x01" * 64) + sof(4, 4) + SOS)
    add("dqt-16bit", SOI + segment(0xDB, b"\x10" + b"\x00\x01" * 64) + sof(4, 4) + SOS)
    add("dqt-short", SOI + segment(0xDB, b"\x00" + b"\x01" * 10) + sof(4, 4) + SOS)
    add("dqt-two", SOI + segment(0xDB, b"\x00" + b"\x01" * 64 + b"\x01" + b"\x02" * 64) + sof(4, 4) + SOS)
    add("dqt-trailing", SOI + segment(0xDB, b"\x00" + b"\x01" * 64 + b"\x01") + sof(4, 4) + SOS)
    add("jfif", SOI + segment(0xE0, b"JFIF\x00\x01\x02\x01\x00\x48\x00\x48\x00\x00") + sof(4, 4) + SOS)
    add("jfif-cm", SOI + segment(0xE0, b"JFIF\x00\x01\x02\x02\x00\x48\x00\x48\x00\x00") + sof(4, 4) + SOS)
    add("jfif-short", SOI + segment(0xE0, b"JFIF\x00\x01") + sof(4, 4) + SOS)
    add("jfif-seven", SOI + segment(0xE0, b"JFIF\x00\x01\x02") + sof(4, 4) + SOS)
    add("jfif-no-density", SOI + segment(0xE0, b"JFIF\x00\x01\x02\x01") + sof(4, 4) + SOS)
    add("adobe", SOI + segment(0xEE, b"Adobe\x00\x64\x00\x00\x00\x00\x01") + sof(4, 4, layers=4) + SOS)
    add("adobe-short", SOI + segment(0xEE, b"Adobe\x00") + sof(4, 4) + SOS)
    add("adobe-no-transform", SOI + segment(0xEE, b"Adobe\x00\x64\x00") + sof(4, 4) + SOS)
    add("icc-short", SOI + segment(0xE2, b"ICC_PROFILE\x00\x01") + sof(4, 4) + SOS)
    add("icc-ok", SOI + segment(0xE2, b"ICC_PROFILE\x00\x01\x01abc") + sof(4, 4) + SOS)
    add("icc-count-mismatch", SOI + segment(0xE2, b"ICC_PROFILE\x00\x01\x02abc") + sof(4, 4) + SOS)
    add("icc-after-sof", SOI + sof(4, 4) + segment(0xE2, b"ICC_PROFILE\x00\x01") + SOS)
    add("photoshop", SOI + segment(0xED, b"Photoshop 3.0\x008BIM\x03\xed\x00\x00\x00\x00\x00\x10"
                                   + b"\x00" * 16) + sof(4, 4) + SOS)
    add("photoshop-name-eof", SOI + segment(0xED, b"Photoshop 3.0\x008BIM\x03\xed") + sof(4, 4) + SOS)
    add("photoshop-size-eof", SOI + segment(0xED, b"Photoshop 3.0\x008BIM\x03\xed\x00\x00") + sof(4, 4) + SOS)
    add("photoshop-code-eof", SOI + segment(0xED, b"Photoshop 3.0\x008BIM\x03") + sof(4, 4) + SOS)
    add("photoshop-resolution-short", SOI + segment(0xED, b"Photoshop 3.0\x008BIM\x03\xed\x00\x00\x00\x00\x00\x02"
                                                    + b"\x00\x00") + sof(4, 4) + SOS)
    add("exif-garbage", SOI + segment(0xE1, b"Exif\x00\x00garbage") + sof(4, 4) + SOS)
    add("exif-empty", SOI + segment(0xE1, b"Exif\x00\x00") + sof(4, 4) + SOS)
    add("xmp", SOI + segment(0xE1, b"http://ns.adobe.com/xap/1.0/\x00<x/>") + sof(4, 4) + SOS)
    add("mpf-garbage", SOI + segment(0xE2, b"MPF\x00garbage") + sof(4, 4) + SOS)
    add("bad-prefix", b"\xff\xd8\x00" + sof(4, 4) + SOS)
    add("double-sof", SOI + sof(4, 4) + sof(8, 2) + SOS)
    base = encoded("RGB", (4, 4))
    rng = random.Random(1704)
    for index in range(160):
        data = bytearray(base)
        position = rng.randrange(2, min(len(data), 180))
        data[position] = rng.randrange(256)
        add(f"mutation-{index}", bytes(data))
    for cut in range(0, min(len(base), 200), 7):
        add(f"truncated-{cut}", base[:cut])
    base64_cases = []
    for text in ("", "QQ==", "QQ=", "QQ", "QUI=", "QUI", "QUI==", "QUJD", "QUJD=", "QUJD==", "QUJD===", "Q", "Q=",
                 "Q==", "QUJDR", "QUJDRA==", "QUJDRA=", "QU JD", "QUJD\n", " QUJD", "QUJD-_", "QUJD+/==", "é", "QU=D",
                 "=", "==", "===", "QQ===", "QQ=A", "AAAA", "////", "QUJDRA", "QUJDREU", "QUJDREVG", "\x00"):
        try:
            decoded = base64.b64decode(text, validate=True)
            base64_cases.append({"input": text, "ok": decoded.hex()})
        except ValueError as error:
            base64_cases.append({"input": text, "error": type(error).__name__})
    write_json("python-jpeg.json", {"pillow": Image.__version__, "cases": cases, "base64": base64_cases})


# --------------------------------------------------------------------------------------------- JSON corpus

JSON_VALUES = [
    None, True, False, 0, 1, -1, 42, 2**31, 2**53, 2**53 + 1, -(2**63), 10**30, 0.1, -0.5, 1.5, 3.14159,
    123456789.123, 1e16, 1.5e16, 1e15, 123456789012345.6, 1e-4, 1e-5, 1.5e-5, 1e-7, 5e-324, 1.7976931348623157e308,
    2.5e-10, 1e21, 1e22, 0.30000000000000004, 100.25, -0.0001, 0.001234, 1234e-2, "", "plain", "quote\"back\\slash",
    "\n\r\t\b\f\x00\x01\x1f\x7f", "é", "café", "€", "😀", "\u2028\u2029", "\ud800", "\udfff", "a\ud83d", "</script>",
    [], {}, [1, [2, [3]]], {"b": 1, "a": 2}, {"10": 1, "2": 2, "a": 3}, {"nested": {"list": [1, "x", None], "e": {}}},
    [{}, []], {"é": "ü"},
]


def json_corpus():
    cases = []
    for value in JSON_VALUES:
        source = json.dumps(value, ensure_ascii=True, allow_nan=True)
        record = {"input": source,
                  "default": json.dumps(value),
                  "compact": json.dumps(value, separators=(",", ":")),
                  "indent2": json.dumps(value, indent=2),
                  "unicode": json.dumps(value, ensure_ascii=False),
                  "pydantic_indent2": outcome(lambda v: pydantic_core.to_json(v, fallback=str, indent=2).decode(),
                                              value)}
        cases.append(record)
    integral = []
    for value in (1.0, -1.0, 0.0, -0.0, 100.0, 1e15, 2.0**53):
        integral.append({"python_float": repr(value), "default": json.dumps(value),
                         "pydantic": pydantic_core.to_json(value).decode()})
    specials = {"nan": json.dumps(float("nan")), "inf": json.dumps(float("inf")),
                "-inf": json.dumps(float("-inf"))}
    depth = 1
    while True:
        try:
            json.loads("[" * depth + "]" * depth)
        except RecursionError:
            break
        depth += 1
        if depth > 200000:
            break
    parse = []
    for text in ('{"a":1,"a":2}', '{"a":NaN}', '[Infinity]', '[-Infinity]', '1e400', '-1e400', '[1e-400]',
                 '"\\ud800"', '"\\u00e9"', '{"__proto__":1}', ' 1 ', '[1,]', '{"a":1,}', "'x'", '01', '-',
                 '1.', '.5', '1e', '"\x01"', '"\\x"', 'true false', '\ufeff1', '[1]x', '{"a" 1}', 'nul',
                 '"a\u2028b"', '12345678901234567890', '-0', '0e0', '1E+2', '[1.0, 1e2, 1.5e-7]'):
        try:
            value = json.loads(text)
            parse.append({"input": text, "ok": json.dumps(value, ensure_ascii=True, allow_nan=True)})
        except ValueError:
            parse.append({"input": text, "error": "ValueError"})
    write_json("python-json.json", {"cases": cases, "integral_floats": integral, "specials": specials,
                                    "max_parse_depth": depth - 1, "parse": parse})


# --------------------------------------------------------------------------------------------- MCP surfaces

class FakeConnection:
    def __init__(self, responses):
        self.responses = responses
        self.alive = True
        self.calls = []

    def call(self, method, params=None):
        self.calls.append((method, params))
        value = self.responses.get(method)
        if isinstance(value, Exception):
            raise value
        return value

    def close(self):
        self.alive = False


async def mcp_surfaces():
    import anyio
    from mcp.client.session import ClientSession
    from mcp.shared.memory import create_client_server_memory_streams

    server = native_server.mcp._mcp_server
    artifacts = TEMP / "artifacts"
    artifacts.mkdir(mode=0o700)
    os.environ["FAST_CHROME_ARTIFACT_ROOT"] = str(artifacts)
    image = encoded("RGB", (4, 4))
    responses = {"getInfo": {"version": "0.2.1", "protocolVersion": 2, "pageProtocolVersion": 2},
                 "getUserTabs": [{"id": 7, "url": "https://example.test/é", "title": "Café 😀"}],
                 "getTabs": [{"id": 1, "url": "https://example.test/", "title": "Owned"}],
                 "capturePage": {"data": base64.b64encode(image).decode()}}
    native_server.connect = lambda _path: FakeConnection(responses)
    native_server.TABS.clear()
    tab = native_server.Tab("ses_capture", FakeConnection(responses), 1, "https://example.test", True)
    native_server.TABS[tab.key] = tab
    meta = {"sessionID": "ses_capture"}
    shapes = {}
    async with create_client_server_memory_streams() as (client_streams, server_streams):
        async with anyio.create_task_group() as group:
            group.start_soon(lambda: server.run(server_streams[0], server_streams[1],
                                                server.create_initialization_options()))
            async with ClientSession(client_streams[0], client_streams[1]) as client:
                initialized = await client.initialize()
                listed = await client.list_tools()

                async def call(name, arguments, with_meta=True, key=None):
                    result = await client.call_tool(name, arguments, meta=meta if with_meta else None)
                    shapes[key or name] = {"name": name, "arguments": arguments, "meta": with_meta,
                                           "result": result.model_dump(mode="json", by_alias=True,
                                                                       exclude_none=True)}

                await call("status", {}, key="status-success")
                await call("status", {}, with_meta=False, key="status-no-session")
                await call("tabs", {}, key="tabs-unicode")
                await call("observe", {"tab_id": "999"}, key="observe-not-owned")
                await call("observe", {"tab_id": 5}, key="observe-int-tab-id")
                await call("observe", {}, key="observe-missing-tab-id")
                await call("act_steps", {"tab_id": "1", "steps": '[{"label":"x","extra":1}]'},
                           key="act-steps-extra-field")
                await call("act_steps", {"tab_id": "1", "steps": []}, key="act-steps-empty")
                await call("wait_for", {"tab_id": "1", "expect": {}}, key="wait-for-empty-expectation")
                await call("wait_for", {"tab_id": "1", "expect": {"url": "http://example.test/"}},
                           key="wait-for-gate-in-validator")
                await call("screenshot", {"tab_id": "1"}, key="screenshot")
                await call("no_such_tool", {}, key="unknown-tool")
            group.cancel_scope.cancel()
    for shape in shapes.values():
        for block in shape["result"].get("content", []):
            if block.get("type") == "text" and block["text"].startswith("Saved screenshot: "):
                block["text"] = "Saved screenshot: <artifact>/chrome-capture-XXXX/screenshot.jpg"
            if block.get("type") == "image":
                block["data"] = "<base64 jpeg>"
    write_json("python-tools.json", {
        "initialize": initialized.model_dump(mode="json", by_alias=True, exclude_none=True),
        "server_name": server.name, "instructions": server.instructions,
        "tools": [item.model_dump(mode="json", by_alias=True, exclude_none=True) for item in listed.tools],
    })
    write_json("python-call-shapes.json", shapes)


def argument_corpus():
    manager = native_server.mcp._tool_manager
    long = "x" * 8193
    corpus = {
        "status": [{}, {"extra": 1}],
        "tabs": [{}],
        "claim_browser": [{}, {"site": "https://example.com/"}, {"site": None}, {"site": 5}, {"exclusive": True},
                          {"exclusive": "true"}, {"exclusive": "false"}, {"exclusive": "yes"}, {"exclusive": 1},
                          {"exclusive": 0}, {"exclusive": 2}, {"exclusive": "1"}, {"exclusive": "on"},
                          {"timeout_seconds": 30}, {"timeout_seconds": 0.5}, {"timeout_seconds": "30"},
                          {"timeout_seconds": 0}, {"timeout_seconds": 120}, {"timeout_seconds": 120.5},
                          {"timeout_seconds": True}, {"timeout_seconds": -1}, {"timeout_seconds": None}],
        "release_browser": [{"lease_id": "00000000-0000-4000-8000-000000000000"}, {}, {"lease_id": 5},
                            {"lease_id": None}],
        "open_tab": [{"url": "https://example.com/"}, {"url": "https://example.com/", "group_title": "Task"},
                     {"url": "https://example.com/", "group_title": None}, {"url": 5}, {},
                     {"url": "https://example.com/", "group_title": 5}],
        "claim_tab": [{"tab_id": "1"}, {"tab_id": 1}, {"tab_id": "1", "group_title": "x"}],
        "name_group": [{"tab_id": "1", "title": "Task"}, {"tab_id": "1"}, {"tab_id": "1", "title": None}],
        "observe": [{"tab_id": "1"}, {"tab_id": "1", "controls_only": True}, {"tab_id": "1", "controls_only": "true"},
                    {"tab_id": "1", "controls_only": "True"}, {"tab_id": "1", "controls_only": "t"},
                    {"tab_id": "1", "controls_only": "no"}, {"tab_id": "1", "controls_only": 1},
                    {"tab_id": "1", "controls_only": 1.0}, {"tab_id": "1", "controls_only": 0.5},
                    {"tab_id": "1", "controls_only": None}, {"tab_id": 1.5}],
        "wait_for": [{"tab_id": "1", "expect": {"text": "Ready"}}, {"tab_id": "1", "expect": '{"text": "Ready"}'},
                     {"tab_id": "1", "expect": {"url": "/next"}}, {"tab_id": "1", "expect": {"url": "//evil"}},
                     {"tab_id": "1", "expect": {"url": "https://example.com/x"}},
                     {"tab_id": "1", "expect": {"url": "http://example.com/x"}},
                     {"tab_id": "1", "expect": {"url": "/a b"}}, {"tab_id": "1", "expect": {"text": ""}},
                     {"tab_id": "1", "expect": {"text": "x" * 2001}}, {"tab_id": "1", "expect": {"url": long}},
                     {"tab_id": "1", "expect": {"action_label": "Go"}}, {"tab_id": "1", "expect": {"other": 1}},
                     {"tab_id": "1", "expect": {"text": 5}}, {"tab_id": "1", "expect": {}},
                     {"tab_id": "1", "expect": {"text": "a"}, "timeout_ms": 1},
                     {"tab_id": "1", "expect": {"text": "a"}, "timeout_ms": 15000},
                     {"tab_id": "1", "expect": {"text": "a"}, "timeout_ms": 15001},
                     {"tab_id": "1", "expect": {"text": "a"}, "timeout_ms": 0},
                     {"tab_id": "1", "expect": {"text": "a"}, "timeout_ms": "100"},
                     {"tab_id": "1", "expect": {"text": "a"}, "timeout_ms": 100.0},
                     {"tab_id": "1", "expect": {"text": "a"}, "timeout_ms": True},
                     {"tab_id": "1", "expect": None}, {"tab_id": "1", "expect": "not json"},
                     {"tab_id": "1", "expect": "[1]"}],
        "navigate": [{"tab_id": "1", "url": "https://example.com/"}, {"tab_id": "1"}],
        "act": [{"tab_id": "1", "snapshot_id": "s", "action_id": "a"},
                {"tab_id": "1", "snapshot_id": "s", "action_id": "a", "text": "x"},
                {"tab_id": "1", "snapshot_id": "s", "action_id": "a", "text": 5},
                {"tab_id": "1", "snapshot_id": "s", "action_id": "a", "expect": {"text": "x"}},
                {"tab_id": "1", "snapshot_id": "s", "action_id": "a", "expect": '{"text":"x"}'},
                {"tab_id": "1", "snapshot_id": "s", "action_id": "a", "timeout_ms": "5"},
                {"tab_id": "1", "snapshot_id": "s", "action_id": "a", "timeout_ms": 5.0},
                {"tab_id": "1", "snapshot_id": "s"}],
        "act_steps": [{"tab_id": "1", "steps": [{"label": "Go"}]},
                      {"tab_id": "1", "steps": '[{"label": "Go"}]'},
                      {"tab_id": "1", "steps": [{"label": "Go", "kind": "click"}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "kind": "upload"}]},
                      {"tab_id": "1", "steps": [{"label": ""}]}, {"tab_id": "1", "steps": [{"label": "x" * 161}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "role": ""}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "text": ""}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "text": "x" * 2001}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "timeout_ms": 0}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "timeout_ms": 15000}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "timeout_ms": "5"}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "timeout_ms": 5.0}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "expect": {"text": "x"}}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "expect": {"url": "/n"}}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "expect": {"url": "http://x/"}}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "expect": {}}]},
                      {"tab_id": "1", "steps": [{"label": "Go", "extra": 1}]},
                      {"tab_id": "1", "steps": [{"label": 5}]}, {"tab_id": "1", "steps": ["Go"]},
                      {"tab_id": "1", "steps": [{"label": "Go"}] * 10}, {"tab_id": "1", "steps": [{"label": "Go"}] * 11},
                      {"tab_id": "1", "steps": []}, {"tab_id": "1", "steps": {"label": "Go"}},
                      {"tab_id": "1", "steps": [{"label": "Go"}], "snapshot_id": "s", "include_text": True,
                       "timeout_ms": 60000},
                      {"tab_id": "1", "steps": [{"label": "Go"}], "timeout_ms": 60001},
                      {"tab_id": "1", "steps": [{"label": "Go"}], "timeout_ms": "100"},
                      {"tab_id": "1", "steps": [{"label": "Go"}], "include_text": "true"}],
        "upload_file": [{"tab_id": "1", "snapshot_id": "s", "action_id": "a", "path": "/tmp/x.pdf"},
                        {"tab_id": "1", "snapshot_id": "s", "action_id": "a"}],
        "screenshot": [{"tab_id": "1"}],
        "start_recording": [{"tab_id": "1"}, {"tab_id": "1", "fps": 15, "max_seconds": 60},
                            {"tab_id": "1", "fps": "5"}, {"tab_id": "1", "fps": 5.0}, {"tab_id": "1", "fps": 5.5},
                            {"tab_id": "1", "fps": True}, {"tab_id": "1", "fps": 0}, {"tab_id": "1", "fps": 99},
                            {"tab_id": "1", "max_seconds": "7"}],
        "stop_recording": [{"tab_id": "1"}],
        "release": [{"tab_id": "1"}, {"tab_id": "1", "keep_open": True}, {"tab_id": "1", "keep_open": "false"},
                    {"tab_id": "1", "keep_open": None}],
        "paste_1password_field": [
            {"tab_id": "1", "expected_url": "https://example.com/login", "expected_email": "user@example.test",
             "field": "password", "selector": "#p"},
            {"tab_id": "1", "expected_url": "https://example.com/login", "expected_email": "user@example.test",
             "field": "one-time password", "selector": "#otp", "allow_foreground_search": True},
            {"tab_id": "1", "expected_url": "https://example.com/login", "expected_email": "user@example.test",
             "field": "username", "selector": "#u"},
            {"tab_id": "1", "expected_url": "https://example.com/login", "expected_email": "user@example.test",
             "field": "password", "selector": "#p", "lease_id": "00000000-0000-4000-8000-000000000000"},
            {"tab_id": "1", "expected_url": "https://example.com/login", "expected_email": "user@example.test",
             "field": "password", "selector": "#p", "allow_foreground_search": "true"}],
    }
    records = {}
    for name, cases in corpus.items():
        tool = manager.get_tool(name)
        metadata = tool.fn_metadata
        results = []
        for arguments in cases:
            record = {"arguments": arguments}
            try:
                parsed = metadata.arg_model.model_validate(metadata.pre_parse_json(arguments))
                values = {}
                for key, value in parsed.model_dump_one_level().items():
                    if hasattr(value, "model_dump"):
                        value = value.model_dump(mode="json")
                    elif isinstance(value, list):
                        value = [item.model_dump(mode="json") if hasattr(item, "model_dump") else item
                                 for item in value]
                    values[key] = value
                record["accepted"] = json.loads(json.dumps(values, default=repr))
            except Gate as error:
                record["gate"] = error.code
            except Exception as error:  # noqa: BLE001
                errors = getattr(error, "errors", None)
                record["rejected"] = [{"type": item["type"], "loc": [str(part) for part in item["loc"]]}
                                      for item in errors()] if callable(errors) else type(error).__name__
            results.append(record)
        records[name] = results
    write_json("python-arguments.json", records)


# --------------------------------------------------------------------------------------------- test inventory

def inventory():
    """COLLECT_FILE names the saved output of `pytest --collect-only -q` over the reference tests."""
    counts = {}
    for line in Path(os.environ["COLLECT_FILE"]).read_text().splitlines():
        if line.startswith("test_") and "::" in line:
            identifier = line.split("[", 1)[0]
            counts[identifier] = counts.get(identifier, 0) + 1
    functions = []
    for path in sorted(REFERENCE.glob("test_*.py")):
        tree = ast.parse(path.read_text(), filename=str(path))
        for node in tree.body:
            owners = [(None, node)]
            if isinstance(node, ast.ClassDef):
                owners = [(node.name, item) for item in node.body]
            for owner, item in owners:
                if not isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) or not item.name.startswith("test"):
                    continue
                subtests = sum(isinstance(call, ast.Call) and isinstance(call.func, ast.Attribute)
                               and call.func.attr == "subTest" for call in ast.walk(item))
                identifier = f"{path.name}::{owner}::{item.name}" if owner else f"{path.name}::{item.name}"
                functions.append({"id": identifier, "file": path.name, "class": owner, "name": item.name,
                                  "cases": counts.pop(identifier, 0), "subtest_blocks": subtests})
    if counts or any(item["cases"] == 0 for item in functions):
        raise SystemExit(f"collection and AST scan disagree: {sorted(counts)}")
    write_json("../parity/python-inventory.json", {
        "source": "the fast-chrome Python reference (read-only AST scan; case counts from pytest --collect-only)",
        "collected": sum(item["cases"] for item in functions),
        "functions": functions,
    })


def main():
    targets = set(os.environ.get("CAPTURE_ONLY", "tables,unicode,urls,jpeg,json,mcp,arguments,inventory").split(","))
    FIXTURES.mkdir(parents=True, exist_ok=True)
    UNICODE.mkdir(parents=True, exist_ok=True)
    (FIXTURES.parent / "parity").mkdir(parents=True, exist_ok=True)
    if "tables" in targets:
        generate_idna_tables()
        generate_case_tables()
    if "unicode" in targets:
        unicode_corpus()
    if "urls" in targets:
        url_corpus()
    if "jpeg" in targets:
        jpeg_corpus()
    if "json" in targets:
        json_corpus()
    if "mcp" in targets:
        asyncio.run(mcp_surfaces())
    if "arguments" in targets:
        argument_corpus()
    if "inventory" in targets:
        inventory()


main()
